---
- hosts: vagrant
  become: true
  tasks:
    - name: Add ros ppa
      command: sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'

    - name: Add ros keyserver
      command: apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net --recv-key 0xB01FA116

    - name: Install ros full desktop
      apt: >
        update_cache=yes
        state=present
        name={{item}}
      with_items:
        - ros-indigo-desktop
        - python-rosinstall
        - xfce4
        - virtualbox-guest-dkms
        - virtualbox-guest-utils
        - virtualbox-guest-x11

    - name: Init rosdep
      command: rosdep init
      ignore_errors: yes  # will raise if run previously

    - name: Update rosdep
      command: rosdep update

    - name: Add ros vars to env
      lineinfile: >
        dest=/home/vagrant/.bashrc
        line="source /opt/ros/indigo/setup.bash"
        state=present

    - name: Allow non-root to start guest desktop session
      lineinfile: >
        dest=/etc/X11/Xwrapper.config
        regexp="allowed_users=.*$"
        line="allowed_users=anybody"
        state=present
